/*
 * copyright Ammar Bin Ameerdeen
 * All rights reserved
 */
package printare_system;

import java.awt.Color;
import java.awt.Point;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import net.java.balloontip.BalloonTip;
import net.java.balloontip.styles.RoundedBalloonStyle;
import net.java.balloontip.utils.ToolTipUtils;

/**
 *
 * @author Ammar Bin Ameerdeen
 */
public class HibridSale extends IMSFrame {
    
    IMSFrame main ;
    ProductSalePanel pPanel ;
    PrintOrderSalePanel orderPanel ;
    ServicesSalePanel serviceSalePanel ;
    ContentPanel current ;
    /**
     * Creates new form Template_printare
     */
    public HibridSale(IMSFrame parent, boolean modal) {
        super();
        database = new Database();
        database.connect();
        main = parent ;
        
        
        initComponents();
        JLabel jLabels[] = new JLabel[5];
        jLabels[0] = jLabel1;
        jLabels[1] = jLabel2;
        jLabels[2] = jLabel3;
        jLabels[3] = jLabel4;
        
        
        Theme theme = new Theme();
        theme.setTheme(this);
         this.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        super.windowClosing(e);
                        main.setVisible(true);                        
                        dispose();
                    }
                });
         
         // whatever code must come after this
         pPanel = new ProductSalePanel();
         pPanel.setVisible(true);
         centerPanel.add(pPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));
         pPanel.originalLocation = pPanel.getLocation();
         current = pPanel ;
         
         orderPanel = new PrintOrderSalePanel();
         orderPanel.setVisible(false);
         centerPanel.add(orderPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40));
         orderPanel.originalLocation = orderPanel.getLocation();
         
         serviceSalePanel = new ServicesSalePanel();
         serviceSalePanel.setVisible(false);
         centerPanel.add(serviceSalePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40));
         serviceSalePanel.originalLocation = serviceSalePanel.getLocation();
         
         Common common = new Common();
         customerId.setModel(common.getComboBoxModel("customer", "id"));
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = getBackgroundPanel();
        title = getFrameTitle();
        centerPanel = getCenterPanel();
        jLabel3 = new javax.swing.JLabel();
        customerId = new javax.swing.JComboBox();
        customerNameLabel = new javax.swing.JLabel();
        date = new com.toedter.calendar.JDateChooser();
        jXLabel3 = new org.jdesktop.swingx.JXLabel();
        completeSale = new javax.swing.JButton();
        showServices = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        showOrders = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        showProducts = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backgroundPanel.setBackground(Theme.BACKGROUND_COLOR);
        backgroundPanel.setName("backgroundPanel"); // NOI18N
        backgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setBackground(Theme.TITLE_FONT_COLOR);
        title.setText("Sale");
        title.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        title.setName("title");
        backgroundPanel.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));
        backgroundPanel.remove(title);
        backgroundPanel.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(Theme.TITLE_LOCATION));

        centerPanel.setBackground(new java.awt.Color(236, 198, 161));
        centerPanel.setForeground(Theme.FONT_COLOR);
        centerPanel.setName("centerPanel"); // NOI18N
        centerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setForeground(Theme.FONT_COLOR);
        jLabel3.setText("Customer ID");
        jLabel3.setName("jLabel3"); // NOI18N
        centerPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 17, -1, -1));

        customerId.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1" }));
        customerId.setName("customerId"); // NOI18N
        customerId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerIdActionPerformed(evt);
            }
        });
        centerPanel.add(customerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 12, -1, -1));

        customerNameLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        customerNameLabel.setForeground(Theme.FONT_COLOR);
        customerNameLabel.setText("Default");
        customerNameLabel.setName("customerNameLabel"); // NOI18N
        centerPanel.add(customerNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 16, -1, -1));

        date.setName("date"); // NOI18N
        centerPanel.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        jXLabel3.setForeground(Theme.FONT_COLOR);
        jXLabel3.setText("Date");
        jXLabel3.setName("jXLabel3"); // NOI18N
        centerPanel.add(jXLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        completeSale.setBackground(Theme.BUTTON_COLOR);
        completeSale.setText("Complete Sale");
        completeSale.setName("completeSale"); // NOI18N
        completeSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completeSaleActionPerformed(evt);
            }
        });
        centerPanel.add(completeSale, new org.netbeans.lib.awtextra.AbsoluteConstraints(783, 479, 130, 50));

        showServices.setBackground(Theme.SALE_INACTIVE);
        showServices.setName("showServices"); // NOI18N
        showServices.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showServicesMouseClicked(evt);
            }
        });

        jLabel4.setText("Services");
        jLabel4.setName("jLabel4"); // NOI18N
        showServices.add(jLabel4);

        centerPanel.add(showServices, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, 110, 30));

        showOrders.setBackground(Theme.SALE_INACTIVE);
        showOrders.setName("showOrders"); // NOI18N
        showOrders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showOrdersMouseClicked(evt);
            }
        });

        jLabel2.setText("Orders");
        jLabel2.setName("jLabel2"); // NOI18N
        showOrders.add(jLabel2);

        centerPanel.add(showOrders, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, 110, 30));

        showProducts.setBackground(Theme.SALE_ACTIVE);
        showProducts.setName("showProducts"); // NOI18N
        showProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showProductsMouseClicked(evt);
            }
        });

        jLabel1.setText("Products");
        jLabel1.setName("jLabel1"); // NOI18N
        showProducts.add(jLabel1);

        centerPanel.add(showProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 110, 30));

        backgroundPanel.add(centerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 920, 610));

        getContentPane().add(backgroundPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customerIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerIdActionPerformed
        try {
            String query = "SELECT `name` FROM `customer` WHERE `id`='"+customerId.getSelectedItem()+"'";
            ResultSet rs = database.statement.executeQuery(query);
            
            rs.next();
            String name = rs.getString("name");
            customerNameLabel.setText(name);
        } catch (SQLException ex) {
            Logger.getLogger(ProductSale.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_customerIdActionPerformed

    public boolean validateInput(){
        if (date.getDate() == null){
            BalloonTip balloonTip = new BalloonTip(date, "Please select the Sale date");
            balloonTip.setStyle(new RoundedBalloonStyle(5,5,Theme.NOTIFICATIONS_PANEL_COLOR, Theme.NOTIFICATIONS_PANEL_COLOR));
            balloonTip.setOpacity(((float) 0.7));
            
            ToolTipUtils.balloonToToolTip(balloonTip, 0, 2000);
            balloonTip.setVisible(true);
            return false;
        }
        return true;
    }
    private void completeSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completeSaleActionPerformed
        try {
            // record the sale
            if (!validateInput()){
                return;
            }
            orderPanel.close(((String) customerId.getSelectedItem()));
            pPanel.close(date.getDate(),((String) customerId.getSelectedItem()));
            serviceSalePanel.close(date.getDate(), ((String) customerId.getSelectedItem()));
            
            int orderId = orderPanel.loadOrderId();
            String cId = (String) customerId.getSelectedItem();
            int productSaleId = pPanel.getItemSaleId();
            int serviceId = serviceSalePanel.loadServiceSaleId();
            
            String update = "INSERT INTO `sale` (`item_sale_id`,`order_id`,`customer_id`,`service_sale_id`) VALUES('"+productSaleId+"','"+orderId+"','"+cId+"','"+serviceId+"')";
            database.statement.executeUpdate(update);
            // place the order
        } catch (SQLException ex) {
            Logger.getLogger(HibridSale.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        AnimateCenterPanel a = new AnimateCenterPanel(completeSale);
        a.start();
        (new HibridSale(main, true)).setVisible(true);
        
        this.dispose();
        
    }//GEN-LAST:event_completeSaleActionPerformed

    private void showProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showProductsMouseClicked
        // send current to stock
        current.setLocation(new Point(centerPanel.getWidth(),40));
        
        current.setVisible(false);
        current = pPanel ;
        current.setVisible(true);
       
        showProducts.setBackground(Theme.SALE_ACTIVE);
        showServices.setBackground(Theme.SALE_INACTIVE);
        showOrders.setBackground(Theme.SALE_INACTIVE);
    }//GEN-LAST:event_showProductsMouseClicked

    private void showOrdersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showOrdersMouseClicked
        current.setLocation(new Point(centerPanel.getWidth(),40));
       
       // bring products in
       current.setVisible(false);
       current = orderPanel ;
       current.setVisible(true);

        showProducts.setBackground(Theme.SALE_INACTIVE);
        showServices.setBackground(Theme.SALE_INACTIVE);
        showOrders.setBackground(Theme.SALE_ACTIVE);
    }//GEN-LAST:event_showOrdersMouseClicked

    
    private void showServicesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showServicesMouseClicked
        current.setLocation(new Point(centerPanel.getWidth(),40));
        
        // bring products in
        current.setVisible(false);
        current = serviceSalePanel ;
        current.setVisible(true);
        
        showProducts.setBackground(Theme.SALE_INACTIVE);
        showServices.setBackground(Theme.SALE_ACTIVE);
        showOrders.setBackground(Theme.SALE_INACTIVE);
    }//GEN-LAST:event_showServicesMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HibridSale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HibridSale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HibridSale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HibridSale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                HibridSale dialog = new HibridSale(new IMSFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public org.jdesktop.swingx.JXPanel backgroundPanel;
    public javax.swing.JPanel centerPanel;
    public javax.swing.JButton completeSale;
    public javax.swing.JComboBox customerId;
    public javax.swing.JLabel customerNameLabel;
    public com.toedter.calendar.JDateChooser date;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public org.jdesktop.swingx.JXLabel jXLabel3;
    public javax.swing.JPanel showOrders;
    public javax.swing.JPanel showProducts;
    public javax.swing.JPanel showServices;
    public org.jdesktop.swingx.JXLabel title;
    // End of variables declaration//GEN-END:variables
}
