/*
 * copyright Ammar Bin Ameerdeen
 * All rights reserved
 */
package printare_system;

import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ammar Bin Ameerdeen
 */
public class ManagePrintOrders extends ContentPanel {
    Common common ;
    Database database ;
    boolean update;
    /**
     * Creates new form ManageProductsPanel
     */
    public ManagePrintOrders() {
        initComponents();
        common = new Common();
        update = false ;
        database = new Database();
        database.connect();

        updateOrderHistoryTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        orderHistory = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jobs = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        materials = new javax.swing.JTable();

        setBackground(Theme.CENTER_BOX_COLOR);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        orderHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Order Date", "Due Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        orderHistory.setName("orderHistory"); // NOI18N
        orderHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderHistoryMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(orderHistory);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jobs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Job Id", "Width", "Height", "Price"
            }
        ));
        jobs.setName("jobs"); // NOI18N
        jobs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jobsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jobs);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, -1, 180));

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        materials.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Material Name", "Quantity"
            }
        ));
        materials.setName("materials"); // NOI18N
        jScrollPane3.setViewportView(materials);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, -1, 230));
    }// </editor-fold>//GEN-END:initComponents

    private void orderHistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderHistoryMouseClicked
         // update the jobs table
        String Sid =(String) orderHistory.getValueAt(orderHistory.getSelectedRow(), 0);
        int id = Integer.parseInt(Sid);
        updateJobsTable(id);

        // reset the materials table
        DefaultTableModel tableModel = new DefaultTableModel();

        tableModel.addColumn("Material Name");
        tableModel.addColumn("Quantity");
        tableModel.setNumRows(0);

        materials.setModel(tableModel);
    }//GEN-LAST:event_orderHistoryMouseClicked

    private void jobsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jobsMouseClicked
        // update materials  table
        String Sid =(String) jobs.getValueAt(jobs.getSelectedRow(), 0);
        int id = Integer.parseInt(Sid);
        updateMaterialsTable(id);
    }//GEN-LAST:event_jobsMouseClicked

      
    public void updateOrderHistoryTable(){
        try {
        DefaultTableModel tableModel = new DefaultTableModel();
        
        String query = "SELECT `ordered_date`,`id`,`due_date` FROM `print_order`";
        ResultSet rs = database.statement.executeQuery(query);

        tableModel.addColumn("Order ID");
        tableModel.addColumn("Ordered Date");
        tableModel.addColumn("Due Date");

        while(rs.next()){
        // add row by row
        Vector projectDetails = new Vector();

        projectDetails.add(rs.getString("id"));
        projectDetails.add(rs.getString("ordered_date"));
        projectDetails.add(rs.getString("due_date"));
        
        tableModel.addRow(projectDetails);

        }

                
        orderHistory.setModel(tableModel);

        } catch (SQLException e){
            e.printStackTrace();
        }
        
        
    }
    
    public void updateJobsTable(int id){
        try {
        DefaultTableModel tableModel = new DefaultTableModel();
        
        String query = "SELECT `id`,`width`,`height`,`price` FROM `print_order` WHERE `id`='"+id+"'";
        
        ResultSet rs = database.statement.executeQuery(query);

        tableModel.addColumn("Job ID");
        tableModel.addColumn("Width");
        tableModel.addColumn("Height");
        tableModel.addColumn("Price");

        while(rs.next()){
        // add row by row
        Vector projectDetails = new Vector();

        projectDetails.add(rs.getString("id"));
        projectDetails.add(rs.getString("width"));
        projectDetails.add(rs.getString("height"));
        projectDetails.add(rs.getString("price"));
        
        tableModel.addRow(projectDetails);

        }

        jobs.setModel(tableModel);

        } catch (SQLException e){
            e.printStackTrace();
        }
    }
    
    public void updateMaterialsTable(int id){
        try {
        DefaultTableModel tableModel = new DefaultTableModel();
        
        String query = "SELECT `material_name`,`quantity` FROM `material_print` WHERE `print_order_id`='"+id+"'";
        
        ResultSet rs = database.statement.executeQuery(query);

        tableModel.addColumn("Material Name");
        tableModel.addColumn("Quantity");

        while(rs.next()){
        // add row by row
        Vector projectDetails = new Vector();

        projectDetails.add(rs.getString("material_name"));
        projectDetails.add(rs.getString("quantity"));
        
        tableModel.addRow(projectDetails);

        }

        materials.setModel(tableModel);

        } catch (SQLException e){
            e.printStackTrace();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTable jobs;
    public javax.swing.JTable materials;
    public javax.swing.JTable orderHistory;
    // End of variables declaration//GEN-END:variables
}
