/*
 * copyright Ammar Bin Ameerdeen
 * All rights reserved
 */
package printare_system;

import java.awt.Point;

/**
 *
 * @author Ammar Bin Ameerdeen
 */
public class ManageProductsAndServices extends IMSFrame {
    
    IMSFrame main ;
    ContentPanel current ;
    ManageServicePanel manageServices ;
    ManageProductsPanel manageProducts;
    ManageProjectsPanel manageProjects;
    ManagePrintOrders managePrintOrders;
    
    /**
     * Creates new form Template_printare
     */
    public ManageProductsAndServices(IMSFrame parent, boolean modal) {
        super();
        database = new Database();
        main = parent ;
        initComponents();
        Theme theme = new Theme();
        theme.setTheme(this);
         this.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        super.windowClosing(e);
                        main.setVisible(true);                        
                        dispose();
                    }
                });
         
         // whatever code must come after this

         manageProducts = new ManageProductsPanel();
         manageProducts.setVisible(true);
         centerPanel.add(manageProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40));
         current = manageProducts ;

         manageServices = new ManageServicePanel();
         centerPanel.add(manageServices, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40));
         manageServices.setVisible(false);
 
         manageProjects = new ManageProjectsPanel();
         centerPanel.add(manageProjects, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40));
         manageProjects.setVisible(false);

         managePrintOrders = new ManagePrintOrders();
         centerPanel.add(managePrintOrders, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40));
         managePrintOrders.setVisible(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = getBackgroundPanel();
        title = getFrameTitle();
        centerPanel = getCenterPanel();
        showServices = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        showProducts = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        showProjects = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        showPrintOrders = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backgroundPanel.setBackground(Theme.BACKGROUND_COLOR);
        backgroundPanel.setName("backgroundPanel"); // NOI18N
        backgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setBackground(Theme.TITLE_FONT_COLOR);
        title.setText("Manage My Business");
        title.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        title.setName("title"); // NOI18N
        backgroundPanel.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        centerPanel.setBackground(new java.awt.Color(236, 198, 161));
        centerPanel.setName("centerPanel"); // NOI18N
        centerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        showServices.setBackground(Theme.SALE_INACTIVE);
        showServices.setName("showServices"); // NOI18N
        showServices.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showServicesMouseClicked(evt);
            }
        });

        jLabel4.setText("Services");
        jLabel4.setName("jLabel4"); // NOI18N
        showServices.add(jLabel4);

        centerPanel.add(showServices, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, 110, 30));

        showProducts.setBackground(Theme.SALE_ACTIVE);
        showProducts.setName("showProducts"); // NOI18N
        showProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showProductsMouseClicked(evt);
            }
        });

        jLabel1.setText("Products");
        jLabel1.setName("jLabel1"); // NOI18N
        showProducts.add(jLabel1);

        centerPanel.add(showProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 110, 30));

        showProjects.setBackground(Theme.SALE_INACTIVE);
        showProjects.setName("showProjects");
        showProjects.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showProjectsMouseClicked(evt);
            }
        });

        jLabel5.setText("Projects");
        jLabel5.setName("jLabel5"); // NOI18N
        showProjects.add(jLabel5);

        centerPanel.add(showProjects, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 110, 30));

        showPrintOrders.setBackground(Theme.SALE_INACTIVE);
        showPrintOrders.setName("showPrintOrders"); // NOI18N
        showPrintOrders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showPrintOrdersMouseClicked(evt);
            }
        });

        jLabel2.setText("Orders");
        jLabel2.setName("jLabel2"); // NOI18N
        showPrintOrders.add(jLabel2);

        centerPanel.add(showPrintOrders, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 110, 30));

        backgroundPanel.add(centerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 1320, 530));

        getContentPane().add(backgroundPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showServicesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showServicesMouseClicked
        
        // bring products in
        current.setVisible(false);
        current = manageServices ;
        current.setVisible(true);

        showProducts.setBackground(Theme.SALE_INACTIVE);
        showServices.setBackground(Theme.SALE_ACTIVE);
        showProjects.setBackground(Theme.SALE_INACTIVE);
        showPrintOrders.setBackground(Theme.SALE_INACTIVE);
        
        manageServices.revalidate();
    }//GEN-LAST:event_showServicesMouseClicked

    private void showProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showProductsMouseClicked
        // send current to stock
        
        
        current.setVisible(false);
        current = manageProducts ;
        current.setVisible(true);
        
        animate(current);
        
        
        showProducts.setBackground(Theme.SALE_ACTIVE);
        showServices.setBackground(Theme.SALE_INACTIVE);
        showProjects.setBackground(Theme.SALE_INACTIVE);
        showPrintOrders.setBackground(Theme.SALE_INACTIVE);
        
        manageProducts.revalidate();
    }//GEN-LAST:event_showProductsMouseClicked

    private void showProjectsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showProjectsMouseClicked
        
        // bring products in
        current.setVisible(false);
        current = manageProjects ;
        current.setVisible(true);
        
        animate(current);
        
        showProducts.setBackground(Theme.SALE_INACTIVE);
        showServices.setBackground(Theme.SALE_INACTIVE);
        showProjects.setBackground(Theme.SALE_ACTIVE);
        showPrintOrders.setBackground(Theme.SALE_INACTIVE);
        
        manageProjects.revalidate();
    }//GEN-LAST:event_showProjectsMouseClicked

    private void showPrintOrdersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showPrintOrdersMouseClicked
          // bring products in
        current.setVisible(false);
        current = managePrintOrders ;
        current.setVisible(true);
        
        animate(current);
        
        showProducts.setBackground(Theme.SALE_INACTIVE);
        showServices.setBackground(Theme.SALE_INACTIVE);
        showProjects.setBackground(Theme.SALE_INACTIVE);
        showPrintOrders.setBackground(Theme.SALE_ACTIVE);
        
        managePrintOrders.revalidate();
    }//GEN-LAST:event_showPrintOrdersMouseClicked

    public void animate(ContentPanel panel){
        AnimateCenterPanel a = new AnimateCenterPanel(panel,false, new Point(10,panel.getY()),this);
        a.start();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageProductsAndServices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageProductsAndServices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageProductsAndServices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageProductsAndServices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ManageProductsAndServices dialog = new ManageProductsAndServices(new IMSFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public org.jdesktop.swingx.JXPanel backgroundPanel;
    public javax.swing.JPanel centerPanel;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JPanel showPrintOrders;
    public javax.swing.JPanel showProducts;
    public javax.swing.JPanel showProjects;
    public javax.swing.JPanel showServices;
    public org.jdesktop.swingx.JXLabel title;
    // End of variables declaration//GEN-END:variables
}
