/*
 * copyright Ammar Bin Ameerdeen
 * All rights reserved
 */
package printare_system;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Point;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author Ammar Bin Ameerdeen
 */
public class NotificationItem extends javax.swing.JPanel {
    
    Notifications notificationsPanel ;
    Database database ;
    int notificationId ;
    IMSFrame main ;
    
    /**
     * Creates new form NotificationItem
     */
    public NotificationItem(IMSFrame frame, int id) {
        initComponents();
        notificationId = id ;
        main = frame; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        text = new javax.swing.JLabel();
        removeNotification = new javax.swing.JPanel();
        x = new javax.swing.JLabel();

        setBackground(new java.awt.Color(223, 192, 192));
        setPreferredSize(Theme.NOTIFICATION_ITEM_SIZE_DEFAULT);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(Theme.NOTIFICATION_FONT);
        title.setText("Notifcation Title");
        title.setName("title"); // NOI18N
        add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 2, -1, -1));

        text.setText("Notification Text");
        text.setName("text"); // NOI18N
        add(text, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, 30));

        removeNotification.setBackground(new java.awt.Color(250, 177, 177));
        removeNotification.setName("removeNotification"); // NOI18N
        removeNotification.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeNotificationMouseClicked(evt);
            }
        });

        x.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        x.setText("X");
        x.setName("x"); // NOI18N
        removeNotification.add(x);

        add(removeNotification, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 20, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void removeNotificationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeNotificationMouseClicked
        try {
            // update the database
            String update = "UPDATE `notification` SET `notified`='1' WHERE `id`='"+notificationId+"'";
            main.database.statement.executeUpdate(update);
        } catch (SQLException ex) {
            Logger.getLogger(NotificationItem.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        this.setBackground(new Color(173,163,164));
        removeNotification.setBackground(new Color(173,163,164));
        x.setForeground(new Color(173,163,164));
        
        //main.updateNotifications();
    }//GEN-LAST:event_removeNotificationMouseClicked

    
// 
//    public Dimension getSize(){
//    Dimension r = new Dimension(((int)Theme.NOTIFICATION_SIZE_DEFAULT.getWidth()-40), ((int) Theme.NOTIFICATION_SIZE_DEFAULT.getHeight()-20));
//    return r;
//    }
    
    public Point getTextAreaLocation(){
    Point p = new Point (10,10);
    return p;
        }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel removeNotification;
    public javax.swing.JLabel text;
    public javax.swing.JLabel title;
    public javax.swing.JLabel x;
    // End of variables declaration//GEN-END:variables
}
