/*
 * copyright Ammar Bin Ameerdeen
 * All rights reserved
 */
package printare_system;

import java.awt.Point;

/**
 *
 * @author Ammar Bin Ameerdeen
 */
public class PO extends IMSFrame {
    
    IMSFrame main ;
    ContentPanel current ;
    PurchaseOrderSendPanel POSend;
    ViewPOPanel view ;
    /**
     * Creates new form Template_printare
     */
    public PO(IMSFrame parent, boolean modal) {
        super();
        database = new Database();
        main = parent ;
        initComponents();
        Theme theme = new Theme();
        theme.setTheme(this);
         this.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        super.windowClosing(e);
                        main.setVisible(true);                        
                        dispose();
                    }
                });
         
         // whatever code must come after this
         POSend = new PurchaseOrderSendPanel();
         POSend.setLocation(10,10);
         centerPanel.add(POSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60,-1, -1));
         POSend.setVisible(true);
         current = POSend;
     showNewPO.setBackground(Theme.SALE_ACTIVE);
         
         view = new ViewPOPanel();
         view.setLocation(10,10);
         centerPanel.add(view, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60,-1, -1));
         view.setVisible(false);
         
         revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = getBackgroundPanel();
        title = getFrameTitle();
        centerPanel = getCenterPanel();
        showNewPO = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        showViewPO = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        backgroundPanel.setBackground(Theme.BACKGROUND_COLOR);
        backgroundPanel.setName("backgroundPanel"); // NOI18N
        backgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setBackground(Theme.TITLE_FONT_COLOR);
        title.setText("Purchase Orders");
        title.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        title.setName("title"); // NOI18N
        title.setLocation(Theme.TITLE_LOCATION);
        backgroundPanel.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        centerPanel.setBackground(new java.awt.Color(236, 198, 161));
        centerPanel.setName("centerPanel"); // NOI18N
        centerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        showNewPO.setBackground(Theme.SALE_INACTIVE);
        showNewPO.setName("showNewPO"); // NOI18N
        showNewPO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showNewPOMouseClicked(evt);
            }
        });

        jLabel2.setText("New PO");
        jLabel2.setName("jLabel2"); // NOI18N
        showNewPO.add(jLabel2);

        centerPanel.add(showNewPO, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, 110, 30));

        showViewPO.setBackground(Theme.SALE_INACTIVE);
        showViewPO.setName("showViewPO"); // NOI18N
        showViewPO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showViewPOMouseClicked(evt);
            }
        });

        jLabel3.setText("View PO");
        jLabel3.setName("jLabel3"); // NOI18N
        showViewPO.add(jLabel3);

        centerPanel.add(showViewPO, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 10, 110, 30));

        backgroundPanel.add(centerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 1190, 580));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(backgroundPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 1253, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(backgroundPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showNewPOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showNewPOMouseClicked
        // bring products in
        current.setVisible(false);
        current = POSend ;
        current.setVisible(true);

        animate(current);

        showNewPO.setBackground(Theme.SALE_ACTIVE);
        showViewPO.setBackground(Theme.SALE_INACTIVE);
        current.revalidate();
    }//GEN-LAST:event_showNewPOMouseClicked

    private void showViewPOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showViewPOMouseClicked
         current.setVisible(false);
        current = view ;
        current.setVisible(true);

        animate(current);

        showNewPO.setBackground(Theme.SALE_INACTIVE);
        showViewPO.setBackground(Theme.SALE_ACTIVE);
        current.revalidate();
    }//GEN-LAST:event_showViewPOMouseClicked

     public void animate(ContentPanel panel){
//        AnimateCenterPanel a = new AnimateCenterPanel(panel,false, new Point(10,panel.getY()),this);
//        a.start();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PO dialog = new PO(new IMSFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public org.jdesktop.swingx.JXPanel backgroundPanel;
    public javax.swing.JPanel centerPanel;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JPanel showNewPO;
    public javax.swing.JPanel showViewPO;
    public org.jdesktop.swingx.JXLabel title;
    // End of variables declaration//GEN-END:variables
}
