package printare_system;

/*
 * copyright Ammar Bin Ameerdeen
 * All rights reserved
 */

import printare_system.*;

/**
 *
 * @author Ammar Bin Ameerdeen
 */
public class Quotations extends IMSFrame {
    
    IMSFrame main ;
    Database database = new Database();
    ContentPanel current ;
    SendQuotationRequestsPanel sendQuote ;
    ViewSentQuotationRequestsPanel sentQuote ;
    
    /**
     * Creates new form Template_printare
     */
    public Quotations(IMSFrame parent, boolean modal) {
        super();
        database = new Database();
        
        main = parent ;
        initComponents();
        Theme theme = new Theme();
        theme.setTheme(this);
         this.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        super.windowClosing(e);
                        main.setVisible(true);                        
                        dispose();
                    }
                });
         
         
         // whatever code must come after this
         
         sendQuote = new SendQuotationRequestsPanel();
         sendQuote.setLocation(10,10);
         centerPanel.add(sendQuote, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60,-1, -1));
         sendQuote.setVisible(true);
         current = sendQuote;
    
         
         sentQuote = new ViewSentQuotationRequestsPanel();
         sentQuote.setLocation(10,10);
         centerPanel.add(sentQuote, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60,-1, -1));
         sendQuote.setVisible(false);
         
    
    }
    
    public Quotations(){
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = getBackgroundPanel();
        title = getFrameTitle();
        centerPanel = getCenterPanel();
        showViewSent = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        showSendRFQ = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        backgroundPanel.setBackground(Theme.BACKGROUND_COLOR);
        backgroundPanel.setName("backgroundPanel"); // NOI18N
        backgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setBackground(Theme.TITLE_FONT_COLOR);
        title.setText("Request For Quotation");
        title.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        title.setName("title"); // NOI18N
        title.setLocation(Theme.TITLE_LOCATION);
        backgroundPanel.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        centerPanel.setBackground(new java.awt.Color(236, 198, 161));
        centerPanel.setName("centerPanel"); // NOI18N
        centerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        showViewSent.setBackground(Theme.SALE_INACTIVE);
        showViewSent.setName("showViewSent"); // NOI18N
        showViewSent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showViewSentMouseClicked(evt);
            }
        });

        jLabel2.setText("View sent");
        jLabel2.setName("jLabel2"); // NOI18N
        showViewSent.add(jLabel2);

        centerPanel.add(showViewSent, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, 110, 30));

        showSendRFQ.setBackground(Theme.SALE_INACTIVE);
        showSendRFQ.setName("showSendRFQ"); // NOI18N
        showSendRFQ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showSendRFQMouseClicked(evt);
            }
        });

        jLabel3.setText("Send RFQ");
        jLabel3.setName("jLabel3"); // NOI18N
        showSendRFQ.add(jLabel3);

        centerPanel.add(showSendRFQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 10, 110, 30));

        backgroundPanel.add(centerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 1080, 530));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(backgroundPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1133, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(backgroundPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showViewSentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showViewSentMouseClicked
        // bring products in
        current.setVisible(false);
        current = sentQuote ;
        current.setVisible(true);

        //animate(current);

        showViewSent.setBackground(Theme.SALE_ACTIVE);
        showSendRFQ.setBackground(Theme.SALE_INACTIVE);
        current.revalidate();
    }//GEN-LAST:event_showViewSentMouseClicked

    private void showSendRFQMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showSendRFQMouseClicked
        current.setVisible(false);
        current = sendQuote ;
        current.setVisible(true);

        //animate(current);

        showViewSent.setBackground(Theme.SALE_INACTIVE);
        showSendRFQ.setBackground(Theme.SALE_ACTIVE);
        current.revalidate();
    }//GEN-LAST:event_showSendRFQMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quotations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quotations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quotations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quotations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Quotations dialog = new Quotations(new IMSFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public org.jdesktop.swingx.JXPanel backgroundPanel;
    public javax.swing.JPanel centerPanel;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JPanel showSendRFQ;
    public javax.swing.JPanel showViewSent;
    public org.jdesktop.swingx.JXLabel title;
    // End of variables declaration//GEN-END:variables
}
