/*
 * copyright Ammar Bin Ameerdeen
 * All rights reserved
 */
package printare_system;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Ammar Bin Ameerdeen
 */
public class WastedStock extends IMSFrame {
    
    IMSFrame main ;
    String product_name ;
    /**
     * Creates new form Template_printare
     */
    
    public WastedStock(boolean modal, String name) {
        super();
        database = new Database();
        database.connect();
        
        product_name = name ;
        
        initComponents();
        Theme theme = new Theme();
        theme.setTheme(this);
         this.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        super.windowClosing(e);
                        dispose();
                    }
                });
         
         // whatever code must come after this
         this.name.setText(name);
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = getBackgroundPanel();
        title = getFrameTitle();
        centerPanel = getCenterPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        wastedStock = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        reason = new javax.swing.JTextArea();
        removeStock = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        backgroundPanel.setBackground(Theme.BACKGROUND_COLOR);
        backgroundPanel.setName("backgroundPanel"); // NOI18N
        backgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setBackground(Theme.TITLE_FONT_COLOR);
        title.setText("Wasted Stock");
        title.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        title.setName("title"); // NOI18N
        title.setLocation(Theme.TITLE_LOCATION);
        backgroundPanel.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        centerPanel.setBackground(Theme.CENTER_BOX_COLOR);
        centerPanel.setName("centerPanel"); // NOI18N
        centerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Product:");
        jLabel1.setName("jLabel1"); // NOI18N
        centerPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, -1, -1));

        jLabel2.setText("wasted stock quantity");
        jLabel2.setName("jLabel2"); // NOI18N
        centerPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 56, -1, -1));

        jLabel3.setText("reason");
        jLabel3.setName("jLabel3"); // NOI18N
        centerPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 99, -1, -1));

        name.setText("name");
        name.setName("name"); // NOI18N
        centerPanel.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        wastedStock.setText(" ");
        wastedStock.setName("wastedStock"); // NOI18N
        centerPanel.add(wastedStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 260, 30));

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        reason.setColumns(20);
        reason.setRows(5);
        reason.setName("reason"); // NOI18N
        jScrollPane1.setViewportView(reason);

        centerPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, -1));

        removeStock.setText("Remove wasted stock");
        removeStock.setName("removeStock"); // NOI18N
        removeStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeStockActionPerformed(evt);
            }
        });
        centerPanel.add(removeStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, -1, 38));

        backgroundPanel.add(centerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 570, 230));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(backgroundPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 652, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(backgroundPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 368, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void removeStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeStockActionPerformed
        // reduce the stock from system 
            // get stock and then reduce
        try {
            String query = "SELECT `stock` FROM `product` WHERE `name`='"+product_name+"'";
            ResultSet rs = database.statement.executeQuery(query);
            rs.next();
            int currentStock = rs.getInt("stock");
            int stock = currentStock - Integer.parseInt(wastedStock.getText());
            
            // update the stock in the database
            String update = "UPDATE `product` SET `stock`='"+stock+"' WHERE  `name`='"+product_name+"'";
            database.statement.executeUpdate(update);
            
            // record the wasted in wasted stock table
            Common common = new Common();
            String insert = "INSERT INTO `product_waste` (`date`,`quantity`,`product_name`) VALUES('"+common.getFormatDate(new Date(System.currentTimeMillis()))+"','"+wastedStock.getText()+"','"+product_name+"')";
            database.statement.executeUpdate(insert);
            
             // reset text fields
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(WastedStock.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_removeStockActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(WastedStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(WastedStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(WastedStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(WastedStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                
//                WastedStock dialog = new WastedStock(true,"a");
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public org.jdesktop.swingx.JXPanel backgroundPanel;
    public javax.swing.JPanel centerPanel;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel name;
    public javax.swing.JTextArea reason;
    public javax.swing.JButton removeStock;
    public org.jdesktop.swingx.JXLabel title;
    public javax.swing.JTextField wastedStock;
    // End of variables declaration//GEN-END:variables
}
